USE world-cup;

CREATE TABLE TEAM(TeamID CHAR(2) NOT NULL, Team VARCHAR(14), Continent VARCHAR(16), League VARCHAR(9), Population INT, PRIMARY KEY(TeamID));

CREATE TABLE STADIUM(SID CHAR(3) NOT NULL, SName VARCHAR(25), SCity VARCHAR(17), SCapacity INT, PRIMARY KEY(SID));

CREATE TABLE PLAYER(Team VARCHAR(14), TeamID CHAR(2) NOT NULL, PNo INT NOT NULL, Position CHAR(2), PName VARCHAR(25), BirthDate CHAR(10), ShirtName VARCHAR(20), Club VARCHAR(40), Height INT, Weight INT, PRIMARY KEY(PNo, TeamID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID));

CREATE TABLE GAME(GameID CHAR(3) NOT NULL, MatchType CHAR, MatchDate VARCHAR(9), SID CHAR(3), TeamID1 CHAR(2), TeamID2 CHAR(2), Team1_Score INT, Team2_Score INT, PRIMARY KEY(GameID), FOREIGN KEY(TeamID1) REFERENCES TEAM(TeamID), FOREIGN KEY(TeamID2) REFERENCES TEAM(TeamID), FOREIGN KEY(SID) REFERENCES STADIUM(SID));

CREATE TABLE STARTING_LINEUPS(GameID CHAR(3) NOT NULL, TeamID CHAR(2) NOT NULL, PNo INT NOT NULL, PRIMARY KEY(GameID, TeamID, PNo), FOREIGN KEY(GameID) REFERENCES GAME(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PNo) REFERENCES PLAYER(PNo));

CREATE TABLE SUBSTITUTIONS(GameID CHAR(3) NOT NULL, TeamID CHAR(2) NOT NULL, PlayerNoIn INT NOT NULL, Position CHAR(2), PlayerNoOut INT NOT NULL, STime INT, PRIMARY KEY(GameID, TeamID, PlayerNoIn, PlayerNoOut), FOREIGN KEY(GameID) REFERENCES GAME(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PlayerNoIn) REFERENCES PLAYER(PNo), FOREIGN KEY(PlayerNoOut) REFERENCES PLAYER(PNo), FOREIGN KEY(Position) REFERENCES PLAYER(Position));

CREATE TABLE GOALS(GameID CHAR(3) NOT NULL, TeamID CHAR(2) NOT NULL, PNo INT NOT NULL, GTime INT NOT NULL, Penalty CHAR, PRIMARY KEY(GameID, TeamID, PNo, GTime), FOREIGN KEY(GameID) REFERENCES GAME(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PNo) REFERENCES PLAYER(PNo));

CREATE TABLE OWN_GOALS(GameID CHAR(3) NOT NULL, TeamID CHAR(2) NOT NULL, PNo INT NOT NULL, OTime INT NOT NULL, For_TeamID CHAR(2), PRIMARY KEY(GameID, TeamID, PNo, OTime), FOREIGN KEY(GameID) REFERENCES GAME(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PNo) REFERENCES PLAYER(PNo), FOREIGN KEY(For_TeamID) REFERENCES TEAM(TeamID));

CREATE TABLE CARDS(GameID CHAR(3) NOT NULL, TeamID CHAR(2) NOT NULL, PNo INT NOT NULL, Color VARCHAR(6), CTime INT NOT NULL, PRIMARY KEY(GameID, TeamID, PNo, CTime), FOREIGN KEY(GameID) REFERENCES GAME(GameID), FOREIGN KEY(TeamID) REFERENCES TEAM(TeamID), FOREIGN KEY(PNo) REFERENCES PLAYER(PNo));